CREATE TABLE baby_logs (
    id                                     BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    type                                   TEXT,
    profile_name                           TEXT,
    start_date_time                        TIMESTAMP WITH TIME ZONE,
    start_date_time_epoch                  BIGINT,
    created_by_caregiver                   TEXT,
    last_updated_by_caregiver              TEXT,
    note                                   TEXT,
    time_zone                              TEXT,
    sleep_duration_seconds                 INTEGER,
    sleep_end_date_time                    TIMESTAMP WITH TIME ZONE,
    sleep_end_date_time_epoch              BIGINT,
    bottle_feed_type                       TEXT,
    bottle_feed_breast_milk_volume         NUMERIC,
    bottle_feed_breast_milk_volume_unit    TEXT,
    bottle_feed_formula_name               TEXT,
    bottle_feed_formula_volume             NUMERIC,
    bottle_feed_formula_volume_unit        TEXT,
    bottle_feed_volume                     NUMERIC,
    bottle_feed_volume_unit                TEXT,
    solid_feed_food                        TEXT,
    solid_feed_meal                        TEXT,
    diaper_type                            TEXT,
    diaper_detail                          TEXT,
    diaper_dirty_color                     TEXT,
    diaper_dirty_texture                   TEXT,
    medical_medication                     TEXT,
    medical_temperature                    NUMERIC(4,1),
    medical_temperature_unit               TEXT,
    growth_head_size                       NUMERIC(4,1),
    growth_head_size_unit                  TEXT,
    growth_height                          NUMERIC(5,2),
    growth_height_unit                     TEXT,
    growth_weight                          NUMERIC(5,2),
    growth_weight_unit                     TEXT,
    breastfeed_begin_side                  TEXT,
    breastfeed_end_side                    TEXT,
    breastfeed_left_duration_seconds       INTEGER,
    breastfeed_right_duration_seconds      INTEGER,
    pump_duration_seconds                  INTEGER,
    pump_end_date_time                     TIMESTAMP WITH TIME ZONE,
    pump_end_date_time_epoch               BIGINT,
    pump_left_volume                       NUMERIC,
    pump_left_volume_unit                  TEXT,
    pump_right_volume                      NUMERIC,
    pump_right_volume_unit                 TEXT,
    pump_total_volume                      NUMERIC,
    pump_total_volume_unit                 TEXT,
    milestone_milestone                    TEXT,
    vaccine_vaccine                        TEXT,
    routine_routine                        TEXT,
    combo_feed_begin_side                  TEXT,
    combo_feed_end_side                    TEXT,
    combo_feed_left_duration_seconds       INTEGER,
    combo_feed_right_duration_seconds      INTEGER,
    combo_feed_type                        TEXT,
    combo_feed_breast_milk_volume          NUMERIC,
    combo_feed_breast_milk_volume_unit     TEXT,
    combo_feed_formula_name                TEXT,
    combo_feed_formula_volume              NUMERIC,
    combo_feed_formula_volume_unit         TEXT,
    combo_feed_volume                      NUMERIC,
    combo_feed_volume_unit                 TEXT,
    profile_birth_date                     DATE,
    profile_birth_date_adjusted            DATE,
    profile_sex                            TEXT,
    profile_type                           TEXT,
    family_key                             TEXT,
    profile_key                            TEXT,
    activity_key                           TEXT,
    created_at                             TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);